### ISSUE TITLE
The addon won't work help

### ISSUE THREAD

**Issue by enaut** [GKFX/hide-ff-title-bar#4]
I installed the Addon and followed the instructions but my titlebar won't vanish.
What's the next step to debug those problems?

**Comment by edugaedke** [comment]
I don't know if this is the best solution, but it solved my problem.
I'm using Firefox 57 on Fedora with Xorg, and had to do the manual installation.

1. Download the [hide_title_bar.json](https://raw.githubusercontent.com/GKFX/hide-ff-title-bar/master/native/hide_title_bar.json) and saved at /usr/lib64/mozilla/native-messaging-hosts/hide_title_bar.json.
Try the other options, ~/.mozilla/native-messaging-hosts/hide_title_bar.json and /usr/lib/mozilla/native-messaging-hosts/hide_title_bar.json. One of them should work.
Or you can run:
> sudo su
> mkdir -p /usr/lib64/mozilla/native-messaging-hosts/
> wget https://raw.githubusercontent.com/GKFX/hide-ff-title-bar/master/native/hide_title_bar.json -O /usr/lib64/mozilla/native-messaging-hosts/hide_title_bar.json

2. Download the script [native.py](https://raw.githubusercontent.com/GKFX/hide-ff-title-bar/master/native/native.py) to the default directory configured on the json file (/opt/hide-ff-title-bar/native.py).
Set the executable flag on the file.
Or you can run:
> mkdir -p /opt/hide-ff-title-bar/
> wget https://raw.githubusercontent.com/GKFX/hide-ff-title-bar/master/native/native.py -O /opt/hide-ff-title-bar/native.py
> chmod +x /opt/hide-ff-title-bar/native.py

3. I that and looking the python script discovered that one dependency was missing. Installed the wmctrl package and finally it works!
> (for Fedora) dnf install wmctrl

4. Close all your Firefox instances and reopen. It takes 1~2 seconds to remove the title bar.

If it helps someone, let me know! 😃

**Comment by enaut** [comment]
Thank you! The third step - installing the wmctrl was missing for me.
